const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIlDED: 'FETCH_GENDER_FAIDED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAIlDED: 'FETCH_POSITION_FAIDED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIlDED: '    FETCH_ROLE_FAIlDED',

    CREATE_USER_SUCCESS: ' CREATE_USER_SUCCESS',
    CREATE_USER_FAIlDED: 'CREATE_USER_FAIlDED',

    EDIT_USER_SUCCESS: ' EDIT_USER_SUCCESS',
    EDIT_USER_FAIlDED: 'EDIT_USER_FAIlDED',

    DELETE_USER_SUCCESS: ' DELETE_USER_SUCCESS',
    DELETE_USER_FAIlDED: 'DELETE_USER_FAIlDED',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAIlDED: 'FETCH_ALL_USER_FAIlDED',

    FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
    FETCH_TOP_DOCTORS_FAIlDED: 'FETCH_TOP_DOCTORS_FAIlDED',


    FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
    FETCH_ALL_DOCTORS_FAIlDED: 'FETCH_ALL_DOCTORS_FAIlDED',

    SAVE_DETAIL_DOCTORS_SUCCESS: 'SAVE_DETAIL_DOCTORS_SUCCESS',
    SAVE_DETAIL_DOCTORS_FAIlDED: 'SAVE_DETAIL_DOCTORS_FAIlDED',

    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAIlDED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAIlDED',

    FETCH_REQUIRED_DOCTOR_INFOR_START: 'FETCH_REQUIRED_DOCTOR_INFOR_START',
    FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS: 'FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS',
    FETCH_REQUIRED_DOCTOR_INFOR_FAIDED: 'FETCH_REQUIRED_DOCTOR_INFOR_FAIDED',

    FETCH_ALL_SPECIALTY_SUCCESS: 'FETCH_ALL_SPECIALTY_SUCCESS',
    FETCH_ALL_SPECIALTY_FAILED: 'FETCH_ALL_SPECIALTY_FAILED',

    DELETE_SPECIALTY_SUCCESS: 'DELETE_SPECIALTY_SUCCESS',
    DELETE_SPECIALTY_FAILED: 'DELETE_SPECIALTY_FAILED',

    EDIT_SPECIALTY_SUCCESS: 'EDIT_SPECIALTY_SUCCESS',
    EDIT_SPECIALTY_FAILED: 'EDIT_SPECIALTY_FAILED',

    FETCH_ALL_CLINICS_SUCCESS: 'FETCH_ALL_CLINICS_SUCCESS',
    FETCH_ALL_CLINICS_FAILED: 'FETCH_ALL_CLINICS_FAILED',

    DELETE_CLINIC_SUCCESS: 'DELETE_CLINIC_SUCCESS',
    DELETE_CLINIC_FAILED: 'DELETE_CLINIC_FAILED',

    EDIT_CLINIC_SUCCESS: 'EDIT_CLINIC_SUCCESS',
    EDIT_CLINIC_FAILED: 'EDIT_CLINIC_FAILED',

    FETCH_ALL_HANDBOOKS_SUCCESS: 'FETCH_ALL_HANDBOOKS_SUCCESS',
    FETCH_ALL_HANDBOOKS_FAILED: 'FETCH_ALL_HANDBOOKS_FAILED',

    DELETE_HANDBOOK_SUCCESS: 'DELETE_HANDBOOK_SUCCESS',
    DELETE_HANDBOOK_FAILED: 'DELETE_HANDBOOK_FAILED',

    EDIT_HANDBOOK_SUCCESS: 'EDIT_HANDBOOK_SUCCESS',
    EDIT_HANDBOOK_FAILED: 'EDIT_HANDBOOK_FAILED',

    // Appointments
    FETCH_ALL_APPOINTMENTS_SUCCESS: 'FETCH_ALL_APPOINTMENTS_SUCCESS',
    FETCH_ALL_APPOINTMENTS_FAILED: 'FETCH_ALL_APPOINTMENTS_FAILED',

    UPDATE_APPOINTMENT_STATUS_SUCCESS: 'UPDATE_APPOINTMENT_STATUS_SUCCESS',
    UPDATE_APPOINTMENT_STATUS_FAILED: 'UPDATE_APPOINTMENT_STATUS_FAILED',

    // Follow-up
    FETCH_ALL_FOLLOWUP_SUCCESS: 'FETCH_ALL_FOLLOWUP_SUCCESS',
    FETCH_ALL_FOLLOWUP_FAILED: 'FETCH_ALL_FOLLOWUP_FAILED',

})

export default actionTypes;